openapi: 3.0.0
info:
  title: Sample API
  description: Test de OpenApi
  version: 0.1.9
servers:
- url: localhost:8080
  description: Mon server de test
paths:
  /companys:
    get:
      summary: Returns a list of companys.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of company
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
                x-content-type: application/json
  /company/{id}:
    get:
      summary: Returns a user by ID.
      parameters:
      - name: id
        in: path
        description: Parameter description in CommonMark or HTML.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Company'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Company'
                x-content-type: application/json
  /company/{name}:
    get:
      summary: Returns a user by name.
      parameters:
      - name: name
        in: path
        description: Parameter description in CommonMark or HTML.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Company'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Company'
                x-content-type: application/json
  /companyCreate:
    post:
      summary: Creates a Company.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
      responses:
        "301":
          description: Redirect
components:
  schemas:
    Company:
      required:
      - address
      - age
      - id
      - name
      - salary
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
        address:
          type: string
        salary:
          type: number
