/*
 * Sample API
 *
 * Test de OpenApi
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
	"encoding/json"
	"strconv"

	"github.com/gorilla/mux"
)

func CompanyIdGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	id, err := strconv.Atoi(vars["id"])

	if err != nil {
        respondWithError(w, http.StatusBadRequest, "Invalid product ID")
        return
	}

	company, err := GetCompanyById(GetDB(), id)

	if err != nil{
        respondWithError(w, http.StatusInternalServerError, err.Error())
        return
	}

	respondWithJSON(w, http.StatusOK, company)
}

func CompanyNameGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	name := vars["name"]

	company, err := GetCompanyByName(GetDB(), name)

	if err != nil{
        respondWithError(w, http.StatusInternalServerError, err.Error())
        return
	}

	respondWithJSON(w, http.StatusOK, company)
}

func CompanyCreatePost(w http.ResponseWriter, r *http.Request) {
	err := InsertCompany(GetDB())

	if err != nil{
        respondWithError(w, http.StatusInternalServerError, err.Error())
        return
	}

	http.Redirect(w, r, "/companys", 301)
}

func CompanysGet(w http.ResponseWriter, r *http.Request) {
	companys, err := GetCompanys(GetDB())

	if err != nil{
		respondWithError(w, http.StatusInternalServerError, err.Error())
	}

    respondWithJSON(w, http.StatusOK, companys)
}

func respondWithError(w http.ResponseWriter, code int, message string) {
	respondWithJSON(w, code, map[string]string{"error": message})
}

func respondWithJSON(w http.ResponseWriter, code int, payload interface{}) {
    response, _ := json.Marshal(payload)

    w.Header().Set("Content-Type", "application/json")
    w.WriteHeader(code)
    w.Write(response)
}