/*
 * Sample API
 *
 * Test de OpenApi
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {

	Id int32 `json:"id"`

	Name string `json:"name"`

	Age int32 `json:"age"`

	Address string `json:"address"`

	Salary float64 `json:"salary"`
}
